name: Build SunamoSecurity

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoSecurity
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoSecurity/SunamoSecurity.csproj

    - name: Build
      run: dotnet build SunamoSecurity/SunamoSecurity.csproj --configuration Release --no-restore

  test:
    name: Test SunamoSecurity.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoSecurity.Tests/SunamoSecurity.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoSecurity.Tests/SunamoSecurity.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoSecurity.Tests/SunamoSecurity.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
